name       : foomatic-db
version    : '4.0.20171217'
release    : 4
source     :
    - https://www.openprinting.org/download/foomatic/foomatic-db-4.0-20171217.tar.xz : 06baa2c4adb61421baba18fbce99bd77a7f29689193d4f1f0beaaf0734213a9b
license    : GPL-2.0
component  : desktop.core
summary    : The collected knowledge about printers, drivers, and driver options in XML files
description: |
    The collected knowledge about printers, drivers, and driver options in XML files, used by foomatic-db-engine to generate PPD files. It also contains manufacturer-supplied PPD files which got released under free software licenses.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
