name       : foomatic-db
version    : 4.0.20171010
release    : 3
source     :
    - https://www.openprinting.org/download/foomatic/foomatic-db-4.0-20171010.tar.xz : 41f79fc8261082f893225f5bac562f3595c0529f6435331c73d5a0b16956a745
license    : GPL-2.0
component  : desktop.core
summary    : The collected knowledge about printers, drivers, and driver options in XML files
description: |
    The collected knowledge about printers, drivers, and driver options in XML files, used by foomatic-db-engine to generate PPD files. It also contains manufacturer-supplied PPD files which got released under free software licenses.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
