name       : foomatic-db
version    : 4.0.20150819
release    : 1
source     :
    - http://www.openprinting.org/download/foomatic/foomatic-db-4.0-20150819.tar.gz : e9824ae1a7b20894a4be4083e49b66ed828ccc520d55abfdfa835c1eae99dee3
license    : GPL-2.0
summary    : The collected knowledge about printers, drivers, and driver options in XML files
description: |
    The collected knowledge about printers, drivers, and driver options in XML files, used by foomatic-db-engine to generate PPD files. It also contains manufacturer-supplied PPD files which got released under free software licenses.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
